### ISSUE TITLE
Missing several basic terms

### ISSUE THREAD

**Issue by mbollmann** [unimorph/deu#3]
Several very basic terms appear to be missing in this resource, such as:

+ Haus *(house)*
+ Frau *(woman)*
+ Tisch *(table)*
+ Buch *(book)*

However, it includes many weirdly specific compounds or derived terms, such as:

+ Hausmaus *(house mouse)*
+ Tischchen *(diminutive of table)*
+ Frauenzimmer *(dame/wench)*

This makes me wonder if there is some kind of bug in the extraction process that prevents the basic terms from being included?

**Comment by aryamccarthy** [comment]
Hi @mbollmann, good to hear from you!

Yes, there was a bug in the extraction process which I've corrected. I'll push a fix in the coming weeks. If you need data for a given language pronto, send an email to me. Otherwise, I'm planning to update all repos at once.

-am

**Comment by cyriaka90** [comment]
Just out of curiosity, when will the repos be updated? :) I assume that would fix many other issues, like the PR I created in Czech? (https://github.com/unimorph/ces/pull/2)

**Comment by kbatsuren** [comment]
Hi @mbollmann and @aryamccarthy,

The new update fixed this issue. Let's close this issue. Please feel free to open a new one if you find another example.
